### ISSUE TITLE
rest api returns password hash when creating/getting an user

### ISSUE THREAD

**Issue by SrTobi** [HelfenKannJeder/come2help-server#17]
tested with jsondoc playground

**Comment by MariusKl** [comment]
That's a more general problem: You have to post the whole data of user/organisation. Otherwise data will be overwritten by null. And the return of every create/update is the whole user object. We have to specify (tomorrow) which type of updates (e.g. only password or only address) we need and what the return should be

**Comment by MariusKl** [comment]
since we introduced special DTO classes, this is not a problem anymore
